[#release-images-disconnected]
= Maintaining a custom list of release images while disconnected

In some cases, you need to maintain a custom list of release images when the hub cluster has no Internet connection. You can create your own custom list of release images that are available when creating a cluster. Complete the following steps to manage your available release images while disconnected:

. When you are on a connected system, go to the link:https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.7[acm-hive-openshift-releases GitHub repository] to access the available cluster image sets.

. Copy the `clusterImageSets` directory to a system that can access the disconnected {mce-short} cluster.

. Add the mapping between the managed cluster and the disconnected repository with your cluster image sets by completing the following steps that fits your managed cluster:
+
  * For an {ocp-short} managed cluster, see link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/images/image-configuration#images-configuration-registry-mirror_image-configuration[Configuring image registry repository mirroring] for information about using your `ImageContentSourcePolicy` object to complete the mapping. 
 
  * For a managed cluster that is not an {ocp-short} cluster, use the `ManageClusterImageRegistry` custom resource definition to override the location of the image sets. See xref:../cluster_lifecycle/specify_img_registry.adoc#specify-registry-img-on-managed-clusters-for-import[Specifying registry images on managed clusters for import] for information about how to override the cluster for the mapping.  

. Add the YAML files for the images that you want available when you create a cluster by using the console or CLI to manually add the `clusterImageSet` YAML content.

. Modify the `clusterImageSet` YAML files for the remaining {ocp-short} release images to reference the correct offline repository where you store the images. Your updates resemble the following example where `spec.releaseImage` uses your offline image registry of the release image, and the release image is referenced by digest:

+
[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
  name: img<4.x.x>-x86-64-appsub
spec:
  releaseImage: IMAGE_REGISTRY_IPADDRESS_or__DNSNAME/REPO_PATH/ocp-release@sha256:073a4e46289be25e2a05f5264c8f1d697410db66b960c9ceeddebd1c61e58717
----

. Ensure that the images are loaded in the offline image registry that is referenced in the YAML file. 

. Obtain the image digest by running the following command:

+
[source,bash]
----
oc adm release info <tagged_openshift_release_image> | grep "Pull From"
----
+
Replace `<tagged_openshift_release_image>` with the tagged image for the supported {ocp-short} version. See the following example output:

+
[source,bash]
----
Pull From: quay.io/openshift-release-dev/ocp-release@sha256:69d1292f64a2b67227c5592c1a7d499c7d00376e498634ff8e1946bc9ccdddfe
----

+
To learn more about the image tag and digest, see link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/images/managing-images#images-referencing-images-imagestreams_tagging-images[Referencing images in imagestreams].

. Create each of the `clusterImageSets` by entering the following command for each YAML file:

+
----
oc create -f <clusterImageSet_FILE>
----
+
Replace `clusterImageSet_FILE` with the name of the cluster image set file. For example:
+
----
oc create -f img4.11.9-x86_64.yaml
----
+
After running this command for each resource you want to add, the list of available release images are available.

. Alternately you can paste the image URL directly in the create cluster console. Adding the image URL creates new `clusterImageSets` if they do not exist.

. View the list of currently available release images in the console when you are creating a cluster.
