[#deploying-submariner-disconnected]
= Deploying Submariner on disconnected clusters

Deploying Submariner on disconnected clusters can help with security concerns by reducing the risk of external attacks on clusters. To deploy Submariner with {acm} on disconnected clusters, you must first complete the steps outlined in link:../../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments]. 

[#configuring-submariner-disconnected]
== Configuring Submariner on disconnected clusters

After completing the steps in link:../../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments], configure Submariner during the installation to support deployment on disconnected clusters. 

Complete the following steps:

. Mirror the `Submariner Operator bundle` image in the local registry before you deploy Submariner on disconnected clusters.

. Choose the Submariner Operator version that is compatible with your {acm-short} version. For instance, use `0.19.0` for {acm-short} version 2.12.

. Customize `catalogSource` names. By default, `submariner-addon` searches for a `catalogSource` with the name `redhat-operators`. When you use a `catalogSource` with a different name, you must update the value of the `SubmarinerConfig.Spec.subscriptionConfig.Source` parameter in the `SubmarinerConfig` associated with your managed cluster with the custom name of the `catalogSource`.

. Enable `airGappedDeployment` in `SubmarinerConfig`.When installing `submariner-addon` on a managed cluster from the {acm} console, you can select the *Disconnected cluster* option so that Submariner does not make API queries to external servers.

*Note:* If you are installing Submariner by using the APIs, you must set the `airGappedDeployment` parameter to `true` in the `SubmarinerConfig` associated with your managed cluster. 
