---
name: Linting

on:
  pull_request:

jobs:
  asciidoc:
    name: Build AsciiDocs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Install asciidoctor
        run: |
          sudo apt-get install -y asciidoctor

      - name: Build each .adoc with Asciidoctor, fail on WARN or above
        run: |
          find . -name \*.adoc -exec asciidoctor --failure-level WARN --trace --verbose --warnings {} +

      - name: Link Check
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621
        with:
          args: --no-progress --timeout 30 --scheme http --scheme https --require-https "./**/main.html"
          fail: true
